### ISSUE TITLE
<noscript>?

### ISSUE THREAD

**Issue by KrijnHoetmer** [sennykalidien/EW#17]
> We noticed tha JavaScipt has been turned off. Please enable JavaScript and refresh the page to see the content.

Vanuit PE concept is dit natuurlijk not done :) Vergelijk dit met de periode dat je Flash "nodig had" om dingen te doen op het Web. Op bijvoorbeeld een iPhone heb je die keuze helemaal niet. Probeer je HTML zo op te zetten dat je zelfs zonder JavaScript nog iets kunt zien of doen.

**Comment by sennykalidien** [comment]
noscript is eruit. HTML is opgezet zodat je nog steeds iets kan zien als JavaScript uitstaat \o/

**Comment by KoopReynders** [comment]
done
