### ISSUE TITLE
Wat gebeurt er in browsers die Flexbox niet ondersteunen?

### ISSUE THREAD

**Issue by KrijnHoetmer** [sennykalidien/EW#18]
Je gebruikt vrij veel van Flexbox in je CSS. Heb je het getest in browsers die dit niet ondersteunen, en wat kun je hier nog aan verbeteren?

**Comment by sennykalidien** [comment]
Flexbox is vervangen met floating. Daar is veel meer ondersteuning voor!

**Comment by KoopReynders** [comment]
Je kan feautures uit je code schrijven zodat code altijd wordt uitgevoerd, maar je kan ook manieren bedenken dat je best vooruitstrevende technieken kan gebruiken

**Comment by KoopReynders** [comment]
done
