### ISSUE TITLE
Wat doe je in browsers die Promise niet ondersteunen?

### ISSUE THREAD

**Issue by KrijnHoetmer** [sennykalidien/EW#19]
In https://github.com/sennykalidien/EW/blob/master/browser-technologies/week3/opdracht/src/js/modules/data-module.js#L38 gebruik je een `Promise`, maar wat als die niet ondersteund worden (IE8-11 bijvoorbeeld)?

**Comment by sennykalidien** [comment]
Promises zijn eruit (niet meer nodig)

**Comment by KoopReynders** [comment]
done
