### ISSUE TITLE
Wat als querySelector niet ondersteund wordt?

### ISSUE THREAD

**Issue by KrijnHoetmer** [sennykalidien/EW#20]
In https://github.com/sennykalidien/EW/blob/master/browser-technologies/week3/opdracht/src/js/modules/page-module.js#L6 neem je aan dat `querySelector` gewoon werkt. Wat als dat niet zo is?

**Comment by sennykalidien** [comment]
Er is een querySelector fallback (polyfill) toegevoegd voor dit probleem.

**Comment by KrijnHoetmer** [comment]
Grijp niet te snel naar polyfills (waar stop je?), maar probeer het concept van feature detection en cutting the mustard (meer) toe te passen.

**Comment by sennykalidien** [comment]
Feature Detection zit erin :-)

**Comment by KoopReynders** [comment]
done
