### ISSUE TITLE
Pas op met `console.log()` in live code

### ISSUE THREAD

**Issue by KrijnHoetmer** [sennykalidien/EW#21]
Ondanks alle tools die je gebruikt, sluipen er toch nog `console.log()` statements door in je live code (https://github.com/sennykalidien/EW/blob/master/browser-technologies/week3/opdracht/dist/js/app.min.js). Wat als een browser geen console heeft?

**Comment by sennykalidien** [comment]
Alle console-logs zijn eruit :-)

**Comment by KoopReynders** [comment]
done
