### ISSUE TITLE
Core functionaliteit

### ISSUE THREAD

**Issue by KoopReynders** [sennykalidien/EW#22]
> Je hebt een webapp, maar wat gebeurt er als de code niet werkt? Kun je dan de Core functionaliteit nog geven? Bedenk hier een oplossing voor

**Comment by sennykalidien** [comment]
Oplossing is als volgt:

Als JavaScript uitstaat: 
- kan men 1 favoriete t-shirt toevoegen aan het lijstje. 
- blijft de content beschikbaar voor de gebruiker.

**Comment by KoopReynders** [comment]
done
