### ISSUE TITLE
data-id attributen op buttons

### ISSUE THREAD

**Issue by KrijnHoetmer** [sennykalidien/EW#23]
Hoe leest de (eventuele) server deze uit? In JS kun je ze gebruiken, maar hoe zorg je ervoor dat een server ook die waardes doorkrijgt? (name/value)

**Comment by KrijnHoetmer** [comment]
En de pagina ververst ook nog na het klikken op een knop; hoe vang je dit af?

**Comment by sennykalidien** [comment]
- Name / Value pairs toegevoegd aan buttons
- PreventDefault aan (form) event toegevoegd zodat de pagina niet ververst

**Comment by KoopReynders** [comment]
done
