### ISSUE TITLE
Specificity

### ISSUE THREAD

**Issue by vasilisvg** [sennykalidien/EW#5]
Soms worden selectors erg lang. Dit is niet altijd nodig. Kijk eens of dit anders is op te lossen, wellicht met attribute selectors
https://github.com/sennykalidien/EW/blob/master/css-to-the-rescue/opdrachten/week1/opdracht/assets/css/style.css#L203

**Comment by sennykalidien** [comment]
Voor mezelf vind ik het overzichtelijk zo. Ik weet precies waar ik moet zoeken in mijn HTML om deze selector te vinden. Heb je wellicht nog feedback hierop hoe jij bepaalde selectors korter zou benoemen, als leermoment voor volgende week? :-)

**Comment by vasilisvg** [comment]
Dit hebben we in de klas besproken. Er wordt ook gelinkt naar flink wat artikelen. Dit moet je nog wel ff fixen

**Comment by sennykalidien** [comment]
Yes, is duidelijk nu. Is gefixt! :-)
